import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class GolfScore:
    def tally(self, parValues, scoreSheet):
    	strokes = 0
        for value, word in zip(parValues, scoreSheet):
        	if word == 'hole in one':
        		strokes += 1
        	elif word == 'albatross':
        		strokes += value - 3
        	elif word == 'eagle':
        	    strokes += value - 2
        	elif word == 'birdie':
        		strokes += value - 1
        	elif word == 'par':
        		strokes += value
        	elif word == 'bogey':
        		strokes += value + 1
        	elif word == 'double bogey':
        		strokes += value + 2
        	elif word == 'triple bogey':
        		strokes += value + 3
        return strokes

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, hasAnswer, p2):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
	for i in range(len(p0)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str(p0[i]))
	
	sys.stdout.write(str("}") + str(",") + str("{"))
	for i in range(len(p1)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str("\"") + str(p1[i]) + str("\""))
	
	sys.stdout.write(str("}"))
	print(str("]"))
	obj = GolfScore()
	startTime = time.clock()
	answer = obj.tally(p0, p1)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str(p2))
	
	print(str("Your answer:"))
	print(str("\t") + str(answer))
	if (hasAnswer):
		res = answer == p2
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = (1,1,1,1,1,1,1,1,1,5,5,5,5,5,5,5,5,5)
p1 = ("bogey","bogey","bogey","bogey","bogey","bogey","bogey","bogey","bogey","eagle","eagle","eagle","eagle","eagle","eagle","eagle","eagle","eagle")
p2 = 45
all_right = (disabled or KawigiEdit_RunTest(0, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = (3,2,4,2,2,1,1,1,3,2,4,4,4,2,3,1,3,2)
p1 = ("bogey","double bogey","par","double bogey","double bogey","triple bogey","triple bogey","triple bogey","bogey","double bogey","par","par","par","double bogey","bogey","triple bogey","bogey","double bogey")
p2 = 72
all_right = (disabled or KawigiEdit_RunTest(1, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = (3,2,4,2,2,1,1,1,3,2,4,4,4,2,3,1,3,2)
p1 = ("eagle","birdie","albatross","birdie","birdie","par","hole in one","par","eagle","birdie","albatross","albatross","albatross","birdie","eagle","hole in one","eagle","birdie")
p2 = 18
all_right = (disabled or KawigiEdit_RunTest(2, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = (4,1,3,3,4,4,1,4,2,3,3,5,4,1,4,4,2,1)
p1 = ("triple bogey","triple bogey","bogey","par","triple bogey","double bogey","triple bogey","triple bogey","par","eagle","bogey","bogey","birdie","par","triple bogey","eagle","triple bogey","triple bogey")
p2 = 77
all_right = (disabled or KawigiEdit_RunTest(3, p0, p1, True, p2) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))
	
else:
	print(str("Some of the test cases had errors."))

# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
